# Generated by Django 5.2.4 on 2025-07-20 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=100)),
                ('show_type', models.CharField(choices=[('Movie', 'Movie'), ('TV', 'TV Show')], max_length=10)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
