# Generated by Django 5.2.4 on 2025-08-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recommendation', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='review_text',
        ),
        migrations.RemoveField(
            model_name='review',
            name='stars',
        ),
        migrations.RemoveField(
            model_name='show',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Recommendation.show'),
        ),
    ]
